# Generated by Django 3.1 on 2021-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210829_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='note status'),
        ),
    ]
